### ISSUE TITLE
Request for more detail

### ISSUE THREAD

**Issue by davemcg3** [xoscar/image-store#1]
After a review of your design document we have some feedback that we’d like you to address. Some of the positives we saw:

- Your documentation style works well.
- You read through and caught our primary concerns.
- You are very comfortable with the tools used to implement the solution and how to work with them.
- You are aware of ways to save time in development (OpenAPI as an example).

Some of the things we noticed that could be improved:

- You skipped some of the supplementary concerns we had in the prompt, particularly the part about explaining ***why*** you made the decisions you made. We’d love to see some pros versus cons, maybe a discussion of edge cases where they might affect your implementation. We want to see more of your reasoning and logic.
- This felt light on detail, more like a first pass to see if the approach works, and we’d like a more complete document.
- You focused on full-stack, which is nice to know you’re capable there, except the prompt was asking for the front-end architecture.
- We would love to see more discussion of scalability, question 6 in the prompt.

We’d like you to add more detail to the design document keeping the following points in mind:

1. Focus more on the front-end implementation of the feature.
2. Talk about the patterns and practices you would use on the front-end around routing, data validation, state management, caching, pagination, or anything else that stands out to you as an important consideration. Bring up some alternative methods of doing some of those things and why you chose the architecture you did.

**Comment by xoscar** [comment]
Hey @davemcg3 here's the [PR](https://github.com/xoscar/image-store/pull/2) with the requested changes
